import { StyleSheet } from 'react-native';

const AppStyles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 24,
    backgroundColor: '#fff',
  },
  button: {
    backgroundColor: '#007AFF',
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 15,
    marginVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 4,
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '600',
  },
  buttonDisabled: {
    backgroundColor: '#CCCCCC',
    shadowOpacity: 0,
    elevation: 0,
  },
  deviceItemButton: {
    backgroundColor: '#6C7A89',
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 5,
    marginVertical: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deviceItemButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
  },
  weightBox: {
    borderRadius: 40,
    padding: 12,
    margin: 10,
    backgroundColor: '#7678ed',
    borderWidth: 0,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  powerBox: {
    borderRadius: 40,
    padding: 12,
    margin: 10,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  title: {
    fontSize: 28,
    fontWeight: '900',
    color: '#000',
    marginBottom: 0,
    textAlign: 'center',
    letterSpacing: 0.8,
    textShadowColor: 'rgba(0, 0, 0, 0.05)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
    marginTop: 20,
    fontFamily: 'Times New Roman',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#000',
    marginTop: 25,
    marginBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
    paddingBottom: 8,
  },
  connectedText: {
    fontSize: 17,
    color: '#27AE60',
    marginTop: 15,
    marginBottom: 15,
    textAlign: 'center',
    fontWeight: '600',
    paddingVertical: 10,
    backgroundColor: '#EBF9F1',
    borderRadius: 40,
    marginHorizontal: 10,
  },
  dataText: { // Not currently used, but good to have a style
    fontSize: 16,
    color: '#34495E',
    marginVertical: 6,
    lineHeight: 24,
  },
  weightText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
    fontFamily: 'Roboto',
  },
  powerBoxText: {
    fontSize: 20,
    color: '#FFFFFF',
  },
  solarPower: {
    backgroundColor: '#4CAF50',
  },
  acPower: {
    backgroundColor: '#dd2d4a',
  },
  table: {
    borderRadius: 12,
    overflow: 'hidden',
    marginBottom: 20,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
    alignItems: 'center',
  },
  tableHeader: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 8,
    fontWeight: '700',
    backgroundColor: '#ECF0F1',
    color: '#2C3E50',
    textAlign: 'center',
    textTransform: 'uppercase',
    fontSize: 13,
    letterSpacing: 0.5,
  },
  tableCell: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 8,
    textAlign: 'center',
    color: '#34495E',
    fontSize: 15,
    fontFamily: 'Times New Roman',
  },
  header: {
    backgroundColor: '#ECF0F1',
  },
  headerTitle: {
    color: '#2C3E50',
    fontSize: 22,
    fontWeight: 'bold'
  },
  headerTintColor: {
    color: '#1A1A1A'
  }, // Changed from object to direct value
  text: {
    color: '#000',
    fontSize: 16,
  }
});

export const modalStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  alertContainer: {
    width: '80%',
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    padding: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  alertTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
    textAlign: 'center',
  },
  alertMessage: {
    fontSize: 16,
    marginBottom: 20,
    textAlign: 'center',
  },
  alertButton: {
    backgroundColor: '#007AFF',
    borderRadius: 5,
    paddingVertical: 10,
    paddingHorizontal: 20,
  },
  alertButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  header: {
    backgroundColor: '#ECF0F1',
  },
  headerTitle: {
    color: '#2C3E50',
    fontSize: 22,
    fontWeight: 'bold'
  },
  headerTintColor: {
    color: '#1A1A1A'
  }, // Changed from object to direct value
  text: {
    color: '#000',
    fontSize: 16,
  }
});

export const darkStyles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 24,
    backgroundColor: '#121212',
  },
  button: {
    backgroundColor: '#0056b3',
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 15,
    marginVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 4,
  },
  buttonText: {
    color: '#E0E0E0',
    fontSize: 18,
    fontWeight: '600',
  },
  buttonDisabled: {
    backgroundColor: '#555555',
    shadowOpacity: 0,
    elevation: 0,
  },
  deviceItemButton: {
    backgroundColor: '#4A4A4A',
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 5,
    marginVertical: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deviceItemButtonText: {
    color: '#E0E0E0',
    fontSize: 16,
  },
  weightBox: {
    borderRadius: 40,
    padding: 12,
    margin: 10,
    backgroundColor: '#5C5FBB',
    borderWidth: 0,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  powerBox: {
    borderRadius: 40,
    padding: 12,
    margin: 10,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  title: {
    fontSize: 28,
    fontWeight: '900',
    color: '#E0E0E0',
    marginBottom: 0,
    textAlign: 'center',
    letterSpacing: 0.8,
    textShadowColor: 'rgba(255, 255, 255, 0.05)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
    marginTop: 20,
    fontFamily: 'Times New Roman',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#E0E0E0',
    marginTop: 25,
    marginBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
    paddingBottom: 8,
  },
  connectedText: {
    fontSize: 17,
    color: '#82E0AA',
    marginTop: 15,
    marginBottom: 15,
    textAlign: 'center',
    fontWeight: '600',
    paddingVertical: 10,
    backgroundColor: '#1B4D3E',
    borderRadius: 40,
    marginHorizontal: 10,
  },
  dataText: {
    fontSize: 16,
    color: '#B0B0B0',
    marginVertical: 6,
    lineHeight: 24,
  },
  weightText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
    fontFamily: 'Roboto',
  },
  powerBoxText: {
    fontSize: 20,
    color: '#FFFFFF',
  },
  solarPower: {
    backgroundColor: '#388E3C',
  },
  acPower: {
    backgroundColor: '#C62828',
  },
  table: {
    borderRadius: 12,
    overflow: 'hidden',
    marginBottom: 20,
    backgroundColor: '#1E1E1E',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#2C2C2C',
    alignItems: 'center',
  },
  tableHeader: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 8,
    fontWeight: '700',
    backgroundColor: '#2C2C2C',
    color: '#E0E0E0',
    textAlign: 'center',
    textTransform: 'uppercase',
    fontSize: 13,
    letterSpacing: 0.5,
  },
  tableCell: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 8,
    textAlign: 'center',
    color: '#B0B0B0',
    fontSize: 15,
    fontFamily: 'Times New Roman',
  },
  header: {
    backgroundColor: '#1E1E1E',
  },
  headerTitle: {
    color: '#E0E0E0',
    fontSize: 22,
    fontWeight: 'bold'
  },
  headerTintColor: {
    color: '#FFFFFF'
  },
  text: {
    color: '#E0E0E0',
    fontSize: 16,
  }
});

export default AppStyles;